# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'creko' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for creko
  $awsVersion = '~> 2.10.0'
  pod 'AWSCore', $awsVersion
  pod 'AWSCognitoIdentityProvider', $awsVersion
  pod 'AWSRekognition', $awsVersion
  pod 'AWSDynamoDB', $awsVersion
  pod 'AWSS3', $awsVersion

end
