# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'memorybank' do
  use_frameworks!

  $awsVersion = '~> 2.10.0'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
pod 'ImageRow', '~> 4.0'
pod 'Firebase/Analytics'
pod 'Firebase/MLVision'
pod 'Firebase/MLVisionAutoML'
pod 'Firebase/MLVisionObjectDetection'
pod 'Firebase/MLVisionBarcodeModel'
pod 'Firebase/MLVisionFaceModel'
pod 'Firebase/MLVisionLabelModel'
pod 'Firebase/MLVisionTextModel'	
  pod 'AWSCore', $awsVersion
  pod 'AWSCognitoIdentityProvider', $awsVersion
  pod 'AWSRekognition', $awsVersion
  pod 'AWSDynamoDB', $awsVersion
  pod 'AWSS3', $awsVersion
  pod 'Alamofire'
  pod 'MessageKit', :git => 'https://github.com/MessageKit/MessageKit.git', :branch => '3.0.0-swift5'
  pod 'IHKeyboardAvoiding'
  pod 'JTAppleCalendar'
  pod 'ESPullToRefresh'
  pod 'Eureka'
  pod 'SwiftyJSON'
end
