# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'memorybank' do
  use_frameworks!

  $awsVersion = '~> 2.10.0'
  pod 'AWSCore', $awsVersion
  pod 'AWSCognitoIdentityProvider', $awsVersion
  pod 'AWSRekognition', $awsVersion
  pod 'AWSDynamoDB', $awsVersion
  pod 'AWSS3', $awsVersion
  pod 'Alamofire'
  pod 'MessageKit', :git => 'https://github.com/MessageKit/MessageKit.git', :branch => '3.0.0-swift5'

end
